/**
 * Example project demonstrating type-sync usage
 * This shows a complete setup with FastAPI backend and React frontend
 */

// Example directory structure:
/*
my-farm-app/
├── backend/
│   ├── main.py
│   ├── models/
│   │   ├── user.py
│   │   └── post.py
│   └── routers/
│       ├── users.py
│       └── posts.py
├── frontend/
│   ├── src/
│   │   ├── types/           # Generated by type-sync
│   │   │   ├── api.ts
│   │   │   ├── client.ts
│   │   │   ├── hooks.ts
│   │   │   └── schemas.ts
│   │   ├── components/
│   │   └── pages/
│   ├── package.json
│   └── type-sync.config.js
├── .github/
│   └── workflows/
│       └── type-sync.yml
└── README.md
*/

// ===== BACKEND EXAMPLE =====

// backend/main.py
/*
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from routers import users, posts

app = FastAPI(
    title="My FARM App API",
    description="Example API for FARM framework",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(users.router, prefix="/api/v1/users", tags=["users"])
app.include_router(posts.router, prefix="/api/v1/posts", tags=["posts"])

@app.get("/health")
async def health_check():
    return {"status": "healthy"}
*/

// backend/models/user.py
/*
from pydantic import BaseModel, EmailStr
from typing import Optional
from datetime import datetime

class UserBase(BaseModel):
    email: EmailStr
    username: str
    full_name: Optional[str] = None
    is_active: bool = True

class UserCreate(UserBase):
    password: str

class UserUpdate(BaseModel):
    email: Optional[EmailStr] = None
    username: Optional[str] = None
    full_name: Optional[str] = None
    is_active: Optional[bool] = None

class User(UserBase):
    id: int
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True
*/

// backend/routers/users.py
/*
from fastapi import APIRouter, HTTPException, Depends
from typing import List
from models.user import User, UserCreate, UserUpdate

router = APIRouter()

@router.get("/", response_model=List[User])
async def get_users(skip: int = 0, limit: int = 100):
    # Implementation here
    pass

@router.get("/{user_id}", response_model=User)
async def get_user(user_id: int):
    # Implementation here
    pass

@router.post("/", response_model=User)
async def create_user(user: UserCreate):
    # Implementation here
    pass

@router.put("/{user_id}", response_model=User)
async def update_user(user_id: int, user_update: UserUpdate):
    # Implementation here
    pass

@router.delete("/{user_id}")
async def delete_user(user_id: int):
    # Implementation here
    pass
*/

// ===== FRONTEND CONFIGURATION =====

export const exampleConfig = {
  // type-sync.config.js
  serverUrl: "http://localhost:8000",
  outputDir: "./src/types",
  generators: ["typescript", "api-client", "react-hooks"],

  generatorOptions: {
    typescript: {
      enumFormat: "union",
      includeComments: true,
      generateInterfaces: true,
      generateEnums: true,
      strictNullChecks: true,
    },

    "api-client": {
      clientType: "axios",
      includeAuth: true,
      baseURL: "${serverUrl}",
      timeout: 30000,
      retries: 3,
      validation: true,
      errorHandling: "throw",
    },

    "react-hooks": {
      queryClient: "react-query",
      includeInfiniteQueries: true,
      includeOptimisticUpdates: true,
      errorHandling: "throw",
      mutationOptions: {
        onSuccess: "invalidateQueries",
      },
    },
  },

  cache: {
    enabled: true,
    directory: ".type-sync-cache",
    strategy: "adaptive",
    maxAge: 24 * 60 * 60 * 1000, // 24 hours
  },

  watch: {
    enabled: true,
    paths: ["../backend/**/*.py"],
    ignored: ["**/migrations/**", "**/tests/**"],
  },

  plugins: [
    "prettier",
    "eslint",
    {
      name: "custom-header",
      options: {
        header: "// Generated by type-sync - Do not edit manually",
      },
    },
  ],
};

// ===== GENERATED TYPES EXAMPLES =====

// Generated: src/types/schemas.ts
export const exampleGeneratedSchemas = `
// Generated by type-sync - Do not edit manually

export interface UserBase {
  email: string;
  username: string;
  full_name?: string | null;
  is_active: boolean;
}

export interface UserCreate extends UserBase {
  password: string;
}

export interface UserUpdate {
  email?: string | null;
  username?: string | null;
  full_name?: string | null;
  is_active?: boolean | null;
}

export interface User extends UserBase {
  id: number;
  created_at: string; // ISO datetime
  updated_at: string; // ISO datetime
}

export interface Post {
  id: number;
  title: string;
  content: string;
  author_id: number;
  created_at: string;
  updated_at: string;
}

export interface PostCreate {
  title: string;
  content: string;
}

export interface PostUpdate {
  title?: string | null;
  content?: string | null;
}
`;

// Generated: src/types/client.ts
export const exampleGeneratedClient = `
// Generated by type-sync - Do not edit manually

import axios, { AxiosInstance, AxiosRequestConfig } from 'axios';
import { User, UserCreate, UserUpdate, Post, PostCreate, PostUpdate } from './schemas';

export class APIClient {
  private client: AxiosInstance;

  constructor(baseURL: string = 'http://localhost:8000', config?: AxiosRequestConfig) {
    this.client = axios.create({
      baseURL,
      timeout: 30000,
      ...config
    });
    
    this.setupInterceptors();
  }

  private setupInterceptors() {
    // Request interceptor for auth
    this.client.interceptors.request.use((config) => {
      const token = localStorage.getItem('auth_token');
      if (token) {
        config.headers.Authorization = \`Bearer \${token}\`;
      }
      return config;
    });

    // Response interceptor for error handling
    this.client.interceptors.response.use(
      (response) => response,
      (error) => {
        if (error.response?.status === 401) {
          // Handle auth error
          localStorage.removeItem('auth_token');
          window.location.href = '/login';
        }
        return Promise.reject(error);
      }
    );
  }

  // Users endpoints
  async getUsers(params?: { skip?: number; limit?: number }): Promise<User[]> {
    const response = await this.client.get('/api/v1/users', { params });
    return response.data;
  }

  async getUser(userId: number): Promise<User> {
    const response = await this.client.get(\`/api/v1/users/\${userId}\`);
    return response.data;
  }

  async createUser(user: UserCreate): Promise<User> {
    const response = await this.client.post('/api/v1/users', user);
    return response.data;
  }

  async updateUser(userId: number, user: UserUpdate): Promise<User> {
    const response = await this.client.put(\`/api/v1/users/\${userId}\`, user);
    return response.data;
  }

  async deleteUser(userId: number): Promise<void> {
    await this.client.delete(\`/api/v1/users/\${userId}\`);
  }

  // Posts endpoints
  async getPosts(params?: { skip?: number; limit?: number }): Promise<Post[]> {
    const response = await this.client.get('/api/v1/posts', { params });
    return response.data;
  }

  async getPost(postId: number): Promise<Post> {
    const response = await this.client.get(\`/api/v1/posts/\${postId}\`);
    return response.data;
  }

  async createPost(post: PostCreate): Promise<Post> {
    const response = await this.client.post('/api/v1/posts', post);
    return response.data;
  }

  async updatePost(postId: number, post: PostUpdate): Promise<Post> {
    const response = await this.client.put(\`/api/v1/posts/\${postId}\`, post);
    return response.data;
  }

  async deletePost(postId: number): Promise<void> {
    await this.client.delete(\`/api/v1/posts/\${postId}\`);
  }
}

export const apiClient = new APIClient();
`;

// Generated: src/types/hooks.ts
export const exampleGeneratedHooks = `
// Generated by type-sync - Do not edit manually

import { useQuery, useMutation, useQueryClient, UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import { apiClient } from './client';
import { User, UserCreate, UserUpdate, Post, PostCreate, PostUpdate } from './schemas';

// User hooks
export function useUsers(
  params?: { skip?: number; limit?: number },
  options?: UseQueryOptions<User[], Error>
) {
  return useQuery({
    queryKey: ['users', params],
    queryFn: () => apiClient.getUsers(params),
    ...options
  });
}

export function useUser(
  userId: number,
  options?: UseQueryOptions<User, Error>
) {
  return useQuery({
    queryKey: ['users', userId],
    queryFn: () => apiClient.getUser(userId),
    enabled: !!userId,
    ...options
  });
}

export function useCreateUser(
  options?: UseMutationOptions<User, Error, UserCreate>
) {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (user: UserCreate) => apiClient.createUser(user),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['users'] });
    },
    ...options
  });
}

export function useUpdateUser(
  options?: UseMutationOptions<User, Error, { userId: number; user: UserUpdate }>
) {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: ({ userId, user }) => apiClient.updateUser(userId, user),
    onSuccess: (data, { userId }) => {
      queryClient.invalidateQueries({ queryKey: ['users'] });
      queryClient.setQueryData(['users', userId], data);
    },
    ...options
  });
}

export function useDeleteUser(
  options?: UseMutationOptions<void, Error, number>
) {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (userId: number) => apiClient.deleteUser(userId),
    onSuccess: (_, userId) => {
      queryClient.invalidateQueries({ queryKey: ['users'] });
      queryClient.removeQueries({ queryKey: ['users', userId] });
    },
    ...options
  });
}

// Post hooks
export function usePosts(
  params?: { skip?: number; limit?: number },
  options?: UseQueryOptions<Post[], Error>
) {
  return useQuery({
    queryKey: ['posts', params],
    queryFn: () => apiClient.getPosts(params),
    ...options
  });
}

export function usePost(
  postId: number,
  options?: UseQueryOptions<Post, Error>
) {
  return useQuery({
    queryKey: ['posts', postId],
    queryFn: () => apiClient.getPost(postId),
    enabled: !!postId,
    ...options
  });
}

export function useCreatePost(
  options?: UseMutationOptions<Post, Error, PostCreate>
) {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (post: PostCreate) => apiClient.createPost(post),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['posts'] });
    },
    ...options
  });
}

export function useUpdatePost(
  options?: UseMutationOptions<Post, Error, { postId: number; post: PostUpdate }>
) {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: ({ postId, post }) => apiClient.updatePost(postId, post),
    onSuccess: (data, { postId }) => {
      queryClient.invalidateQueries({ queryKey: ['posts'] });
      queryClient.setQueryData(['posts', postId], data);
    },
    ...options
  });
}

export function useDeletePost(
  options?: UseMutationOptions<void, Error, number>
) {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (postId: number) => apiClient.deletePost(postId),
    onSuccess: (_, postId) => {
      queryClient.invalidateQueries({ queryKey: ['posts'] });
      queryClient.removeQueries({ queryKey: ['posts', postId] });
    },
    ...options
  });
}
`;

// ===== USAGE EXAMPLES =====

// Example React component using generated hooks
export const exampleReactComponent = `
import React from 'react';
import { useUsers, useCreateUser, useDeleteUser } from '../types/hooks';
import { UserCreate } from '../types/schemas';

export function UserList() {
  const { data: users, isLoading, error } = useUsers();
  const createUserMutation = useCreateUser();
  const deleteUserMutation = useDeleteUser();

  const handleCreateUser = async (userData: UserCreate) => {
    try {
      await createUserMutation.mutateAsync(userData);
      console.log('User created successfully!');
    } catch (error) {
      console.error('Failed to create user:', error);
    }
  };

  const handleDeleteUser = async (userId: number) => {
    if (window.confirm('Are you sure?')) {
      await deleteUserMutation.mutateAsync(userId);
    }
  };

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>Error: {error.message}</div>;

  return (
    <div>
      <h1>Users</h1>
      {users?.map(user => (
        <div key={user.id}>
          <h3>{user.full_name || user.username}</h3>
          <p>{user.email}</p>
          <button onClick={() => handleDeleteUser(user.id)}>
            Delete
          </button>
        </div>
      ))}
    </div>
  );
}
`;

// Package.json scripts example
export const examplePackageScripts = {
  scripts: {
    "type-sync": "type-sync sync",
    "type-sync:watch": "type-sync watch",
    "type-sync:validate": "type-sync validate",
    "dev:with-types": 'concurrently "npm run dev" "npm run type-sync:watch"',
    "build:with-types": "npm run type-sync && npm run build",
    precommit: "type-sync sync && git add src/types",
  },
  husky: {
    hooks: {
      "pre-commit": "lint-staged && npm run type-sync",
    },
  },
  "lint-staged": {
    "**/*.py": ["npm run type-sync"],
    "src/types/**/*.ts": ["eslint --fix", "prettier --write"],
  },
};

// CI/CD workflow example
export const exampleCIWorkflow = `
name: Type Sync
on:
  push:
    branches: [main, develop]
    paths: ['backend/**/*.py']
  pull_request:
    branches: [main, develop]

jobs:
  type-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          cd frontend && npm ci
          cd backend && pip install -r requirements.txt
      
      - name: Start FastAPI server
        run: |
          cd backend
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 10
      
      - name: Run type sync
        run: |
          cd frontend
          npx type-sync sync
      
      - name: Validate types
        run: |
          cd frontend
          npm run type-check
      
      - name: Commit changes
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add frontend/src/types
          git diff --staged --quiet || git commit -m "chore: update generated types [skip ci]"
          git push
`;

export default {
  exampleConfig,
  exampleGeneratedSchemas,
  exampleGeneratedClient,
  exampleGeneratedHooks,
  exampleReactComponent,
  examplePackageScripts,
  exampleCIWorkflow,
};
