# docker-compose.dev.yml (project root)
services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: farm
      MONGO_INITDB_ROOT_PASSWORD: development
    volumes:
      - mongodb_data:/data/db
      - ./tools/dev-server/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  ollama_models:
  redis_data:
