import type { AIProvider } from "../explanation/engine";

export class MockProvider implements AIProvider {
  private delay: number;

  constructor(delay: number = 500) {
    this.delay = delay;
  }

  async generateExplanation(prompt: string, context: string): Promise<string> {
    // Simulate AI processing delay
    await new Promise((resolve) => setTimeout(resolve, this.delay));

    // Generate a mock explanation based on the context
    const lines = context.split("\n");
    const firstLine = lines[0] || "";

    // Simple heuristics to generate explanations
    if (
      firstLine.includes("function ") ||
      (firstLine.includes("const ") && firstLine.includes("="))
    ) {
      return this.generateFunctionExplanation(context);
    } else if (firstLine.includes("class ")) {
      return this.generateClassExplanation(context);
    } else if (
      firstLine.includes("interface ") ||
      firstLine.includes("type ")
    ) {
      return this.generateTypeExplanation(context);
    } else if (
      firstLine.includes("export ") &&
      firstLine.includes("const ") &&
      context.includes("React")
    ) {
      return this.generateComponentExplanation(context);
    }

    return this.generateGenericExplanation(context);
  }

  private generateFunctionExplanation(context: string): string {
    const lines = context.split("\n");
    const functionLine = lines[0];

    // Extract function name
    const nameMatch = functionLine.match(/(?:function\s+|const\s+)(\w+)/);
    const functionName = nameMatch ? nameMatch[1] : "this function";

    // Check if it's async
    const isAsync = functionLine.includes("async");

    // Check parameters
    const paramMatch = functionLine.match(/\(([^)]*)\)/);
    const hasParams = paramMatch && paramMatch[1].trim().length > 0;

    return `## ${functionName}

**Type**: ${isAsync ? "Async " : ""}Function

**Purpose**: This ${isAsync ? "asynchronous " : ""}function ${
      hasParams ? "accepts parameters and " : ""
    }performs a specific operation in the codebase.

**Key Features**:
- ${
      isAsync
        ? "🔄 Asynchronous execution with Promise-based return"
        : "⚡ Synchronous execution"
    }
- ${
      hasParams
        ? "📥 Accepts input parameters for processing"
        : "🎯 No-parameter function"
    }
- 🏗️ Part of the application's business logic

**Usage Context**: 
This function appears to be a utility or business logic function that handles ${
      hasParams ? "parameterized operations" : "specific functionality"
    } within the application.

*Note: This is a mock explanation. In production, this would be generated by an AI model with deep code understanding.*`;
  }

  private generateClassExplanation(context: string): string {
    const lines = context.split("\n");
    const classLine = lines[0];

    // Extract class name
    const nameMatch = classLine.match(/class\s+(\w+)/);
    const className = nameMatch ? nameMatch[1] : "this class";

    // Check for inheritance
    const extendsMatch = classLine.match(/extends\s+(\w+)/);
    const implementsMatch = classLine.match(/implements\s+([^{]+)/);

    return `## ${className}

**Type**: Class Definition

**Purpose**: This class defines a reusable object template with encapsulated data and methods.

**Key Features**:
- 🏗️ Object-oriented design pattern
- ${extendsMatch ? `🔗 Extends ${extendsMatch[1]}` : "🆕 Base class"}
- ${
      implementsMatch
        ? `✅ Implements ${implementsMatch[1].trim()}`
        : "🎯 Concrete implementation"
    }
- 📦 Encapsulates related functionality

**Architecture**:
This class appears to be part of the application's core architecture, providing ${
      extendsMatch ? "extended functionality" : "foundational capabilities"
    } for the system.

**Usage Context**: 
Typically instantiated to create objects that ${
      implementsMatch ? "conform to specific contracts" : "provide specific functionality"
    } within the application.

*Note: This is a mock explanation. In production, this would be generated by an AI model with deep code understanding.*`;
  }

  private generateTypeExplanation(context: string): string {
    const lines = context.split("\n");
    const typeLine = lines[0];

    // Extract type name
    const nameMatch = typeLine.match(/(?:interface|type)\s+(\w+)/);
    const typeName = nameMatch ? nameMatch[1] : "this type";

    const isInterface = typeLine.includes("interface");

    return `## ${typeName}

**Type**: ${isInterface ? "Interface" : "Type Alias"} Definition

**Purpose**: This ${
      isInterface ? "interface" : "type"
    } defines the structure and contract for data or objects in the system.

**Key Features**:
- 🏷️ Type safety and structure definition
- ${
      isInterface
        ? "🔌 Contract for implementation"
        : "🎯 Type alias for reusability"
    }
- 📋 Documentation through type definitions
- 🛡️ Compile-time validation

**Usage Context**: 
This ${
      isInterface ? "interface" : "type"
    } is used throughout the codebase to ensure type safety and provide clear contracts for data structures and API boundaries.

**Benefits**:
- Improves code maintainability
- Provides IDE autocompletion and error checking
- Serves as living documentation

*Note: This is a mock explanation. In production, this would be generated by an AI model with deep code understanding.*`;
  }

  private generateComponentExplanation(context: string): string {
    const lines = context.split("\n");
    const componentLine = lines[0];

    // Extract component name
    const nameMatch = componentLine.match(/const\s+(\w+)/);
    const componentName = nameMatch ? nameMatch[1] : "this component";

    // Check for props
    const hasProps = context.includes("props") || context.includes(":");

    return `## ${componentName}

**Type**: React Component

**Purpose**: This React component renders UI elements and manages component-specific logic and state.

**Key Features**:
- ⚛️ React functional component
- ${hasProps ? "📥 Accepts props for customization" : "🎯 Self-contained component"}
- 🎨 Handles UI rendering and user interactions
- 🔄 May manage local state and side effects

**Component Architecture**:
This component is part of the application's UI layer, responsible for rendering specific interface elements and handling user interactions.

**Usage Context**: 
Used within the React component tree to provide ${
      hasProps ? "configurable" : "static"
    } UI functionality. Can be composed with other components to build complex interfaces.

**Best Practices Demonstrated**:
- Functional component pattern
- Clear separation of concerns
- Reusable component design

*Note: This is a mock explanation. In production, this would be generated by an AI model with deep code understanding.*`;
  }

  private generateGenericExplanation(context: string): string {
    const lines = context.split("\n");
    const firstLine = lines[0] || "";

    // Try to identify what kind of code this might be
    let codeType = "code block";
    if (firstLine.includes("export")) codeType = "exported module";
    if (firstLine.includes("import")) codeType = "import statement";
    if (firstLine.includes("const") || firstLine.includes("let") || firstLine.includes("var")) {
      codeType = "variable declaration";
    }

    return `## Code Analysis

**Type**: ${codeType.charAt(0).toUpperCase() + codeType.slice(1)}

**Purpose**: This code appears to be part of the application's implementation, contributing to the overall functionality.

**Key Observations**:
- 📝 Well-structured code following standard conventions
- 🏗️ Part of the larger codebase architecture
- 🔧 Implements specific functionality or configuration
- 📦 Contributes to the module's exported interface

**Context**: 
This code segment plays a role in the application's operation, whether for configuration, utility functions, or core business logic.

**Recommendations**:
- Consider adding documentation comments for better maintainability
- Ensure consistent coding style with the rest of the codebase
- Validate input parameters and handle edge cases appropriately

*Note: This is a mock explanation. In production, this would be generated by an AI model with deep code understanding and access to the full codebase context.*`;
  }
}