# .github/workflows/docker-tests.yml
name: Docker Integration Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  docker-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build CLI
        run: pnpm build

      - name: Run Docker Manager unit tests
        run: pnpm test:docker-manager
        # Only run Docker tests on platforms where Docker is reliably available
        if: matrix.os == 'ubuntu-latest'

      - name: Run Docker integration tests
        run: pnpm test:docker-integration
        if: matrix.os == 'ubuntu-latest' # Only run on Linux for Docker

      - name: Test template generation
        run: pnpm test:templates

      - name: Debug environment
        run: |
          echo "Node version: $(node --version)"
          echo "pnpm version: $(pnpm --version)"
          echo "Available scripts:"
          cat package.json | grep -A 10 '"scripts"'
